name = "legacy-router"
main = "src/index.js"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "para.garden/legacy", zone_name = "para.garden" },
  { pattern = "para.garden/legacy/*", zone_name = "para.garden" },
]
